In [3]:
!pip install nltk


In [4]:
paragraph="""Avengers: Endgame is a 2019 American superhero film based on the Marvel Comics superhero team the Avengers. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the direct sequel to Avengers: Infinity War (2018) and the 22nd film in the Marvel Cinematic Universe (MCU). Directed by Anthony and Joe Russo and written by Christopher Markus and Stephen McFeely, the film features an ensemble cast which includes Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Don Cheadle, Paul Rudd, Brie Larson, Karen Gillan, Danai Gurira, Benedict Wong, Jon Favreau, Bradley Cooper, Gwyneth Paltrow, and Josh Brolin. In the film, the surviving members of the Avengers and their allies attempt to reverse Thanos's actions in Infinity War which erased half of all life in the universe.

"""

In [5]:
paragraph

"Avengers: Endgame is a 2019 American superhero film based on the Marvel Comics superhero team the Avengers. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the direct sequel to Avengers: Infinity War (2018) and the 22nd film in the Marvel Cinematic Universe (MCU). Directed by Anthony and Joe Russo and written by Christopher Markus and Stephen McFeely, the film features an ensemble cast which includes Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Don Cheadle, Paul Rudd, Brie Larson, Karen Gillan, Danai Gurira, Benedict Wong, Jon Favreau, Bradley Cooper, Gwyneth Paltrow, and Josh Brolin. In the film, the surviving members of the Avengers and their allies attempt to reverse Thanos's actions in Infinity War which erased half of all life in the universe.\n\n"

In [6]:
 import nltk
 from nltk.stem import PorterStemmer
 from nltk.corpus import stopwords


In [7]:
## tokenization -- paragraphs into sentences -- into words


import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

# Download the 'punkt_tab' data package
nltk.download('punkt_tab')

# Tokenize the paragraph into sentences
sentences = nltk.sent_tokenize(paragraph)

# Print the sentences
print(sentences)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


['Avengers: Endgame is a 2019 American superhero film based on the Marvel Comics superhero team the Avengers.', 'Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the direct sequel to Avengers: Infinity War (2018) and the 22nd film in the Marvel Cinematic Universe (MCU).', 'Directed by Anthony and Joe Russo and written by Christopher Markus and Stephen McFeely, the film features an ensemble cast which includes Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Don Cheadle, Paul Rudd, Brie Larson, Karen Gillan, Danai Gurira, Benedict Wong, Jon Favreau, Bradley Cooper, Gwyneth Paltrow, and Josh Brolin.', "In the film, the surviving members of the Avengers and their allies attempt to reverse Thanos's actions in Infinity War which erased half of all life in the universe."]


In [8]:
type(sentences)

list

In [9]:
stemmer=PorterStemmer()

In [10]:
stemmer.stem('stemming')

'stem'

In [11]:
from nltk.stem import WordNetLemmatizer

In [12]:
lemmatizer=WordNetLemmatizer()

In [15]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
lemmatizer.lemmatize('drinking')

'drinking'

In [14]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [17]:
len(sentences)

4

In [18]:
import re
corpus=[]
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z]',' ',sentences[i])
    review=review.lower()
    corpus.append(review)

In [19]:
corpus

['avengers  endgame is a      american superhero film based on the marvel comics superhero team the avengers ',
 'produced by marvel studios and distributed by walt disney studios motion pictures  it is the direct sequel to avengers  infinity war        and the   nd film in the marvel cinematic universe  mcu  ',
 'directed by anthony and joe russo and written by christopher markus and stephen mcfeely  the film features an ensemble cast which includes robert downey jr   chris evans  mark ruffalo  chris hemsworth  scarlett johansson  jeremy renner  don cheadle  paul rudd  brie larson  karen gillan  danai gurira  benedict wong  jon favreau  bradley cooper  gwyneth paltrow  and josh brolin ',
 'in the film  the surviving members of the avengers and their allies attempt to reverse thanos s actions in infinity war which erased half of all life in the universe ']

In [20]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
nltk.download('stopwords') # Download the 'stopwords' resource

stemmer = PorterStemmer()

## stemming

for i in corpus :
  words = nltk.word_tokenize(i)
  for word in words:
    if word not in set(stopwords.words('english')):
      print(stemmer.stem(word))



aveng
endgam
american
superhero
film
base
marvel
comic
superhero
team
aveng
produc
marvel
studio
distribut
walt
disney
studio
motion
pictur
direct
sequel
aveng
infin
war
nd
film
marvel
cinemat
univers
mcu
direct
anthoni
joe
russo
written
christoph
marku
stephen
mcfeeli
film
featur
ensembl
cast
includ
robert
downey
jr
chri
evan
mark
ruffalo
chri
hemsworth
scarlett
johansson
jeremi
renner
cheadl
paul
rudd
brie
larson
karen
gillan
danai
gurira
benedict
wong
jon
favreau
bradley
cooper
gwyneth
paltrow
josh
brolin
film
surviv
member
aveng
alli
attempt
revers
thano
action
infin
war
eras
half
life
univers


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [21]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [22]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
nltk.download('stopwords')  # Download stopwords if not already downloaded
nltk.download('wordnet')  # Download wordnet if not already downloaded
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

## lemmatization

for i in corpus:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemmatizer.lemmatize(word))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


avenger
endgame
american
superhero
film
based
marvel
comic
superhero
team
avenger
produced
marvel
studio
distributed
walt
disney
studio
motion
picture
direct
sequel
avenger
infinity
war
nd
film
marvel
cinematic
universe
mcu
directed
anthony
joe
russo
written
christopher
markus
stephen
mcfeely
film
feature
ensemble
cast
includes
robert
downey
jr
chris
evans
mark
ruffalo
chris
hemsworth
scarlett
johansson
jeremy
renner
cheadle
paul
rudd
brie
larson
karen
gillan
danai
gurira
benedict
wong
jon
favreau
bradley
cooper
gwyneth
paltrow
josh
brolin
film
surviving
member
avenger
ally
attempt
reverse
thanos
action
infinity
war
erased
half
life
universe


In [23]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(binary=True)

In [24]:
X=cv.fit_transform(corpus)

In [25]:
cv.vocabulary_

{'avengers': 8,
 'endgame': 29,
 'is': 44,
 'american': 3,
 'superhero': 79,
 'film': 35,
 'based': 9,
 'on': 64,
 'the': 83,
 'marvel': 57,
 'comics': 20,
 'team': 81,
 'produced': 68,
 'by': 14,
 'studios': 78,
 'and': 5,
 'distributed': 26,
 'walt': 87,
 'disney': 25,
 'motion': 61,
 'pictures': 67,
 'it': 45,
 'direct': 23,
 'sequel': 76,
 'to': 85,
 'infinity': 43,
 'war': 88,
 'nd': 62,
 'in': 41,
 'cinematic': 19,
 'universe': 86,
 'mcu': 59,
 'directed': 24,
 'anthony': 6,
 'joe': 47,
 'russo': 74,
 'written': 91,
 'christopher': 18,
 'markus': 56,
 'stephen': 77,
 'mcfeely': 58,
 'features': 34,
 'an': 4,
 'ensemble': 30,
 'cast': 15,
 'which': 89,
 'includes': 42,
 'robert': 71,
 'downey': 28,
 'jr': 51,
 'chris': 17,
 'evans': 32,
 'mark': 55,
 'ruffalo': 73,
 'hemsworth': 40,
 'scarlett': 75,
 'johansson': 48,
 'jeremy': 46,
 'renner': 69,
 'don': 27,
 'cheadle': 16,
 'paul': 66,
 'rudd': 72,
 'brie': 12,
 'larson': 53,
 'karen': 52,
 'gillan': 36,
 'danai': 22,
 'gurira': 

In [26]:
corpus[0]

'avengers  endgame is a      american superhero film based on the marvel comics superhero team the avengers '

In [27]:
X[0].toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0]])

In [28]:
## Apply Stopwords.Lemmatize

import re
corpus=[]
for i in range(len(sentences)):

    review=re.sub('[^a-zA-Z]',' ',sentences[i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [29]:
## Baag of words

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(binary=True,ngram_range=(1,1),max_features=10)

In [31]:
X=cv.fit_transform(corpus)

In [32]:
cv.vocabulary_

{'avenger': np.int64(2),
 'film': np.int64(5),
 'marvel': np.int64(7),
 'infinity': np.int64(6),
 'war': np.int64(9),
 'universe': np.int64(8),
 'anthony': np.int64(0),
 'brie': np.int64(4),
 'bradley': np.int64(3),
 'attempt': np.int64(1)}

In [33]:
corpus[0]

'avenger endgame american superhero film based marvel comic superhero team avenger'

In [34]:
X[0].toarray()

array([[0, 0, 1, 0, 0, 1, 0, 1, 0, 0]])

In [35]:
## TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer()

In [38]:
corpus[0]

'avenger endgame american superhero film based marvel comic superhero team avenger'

In [39]:
X[0].toarray()

array([[0, 0, 1, 0, 0, 1, 0, 1, 0, 0]])